{% set name = "pytag" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/yourusername/{{ name }}/archive/{{ version }}.tar.gz
  sha256: # You'll need to add this after creating the release

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - pytag
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/yourusername/{{ name }}
  license: Unlicense
  license_family: Public-Domain
  license_file: UNLICENSE
  summary: A minimal Python library for programmatic HTML generation
  doc_url: https://github.com/yourusername/{{ name }}
  dev_url: https://github.com/yourusername/{{ name }}

extra:
  recipe-maintainers:
    - your-github-username 