from .core import Tag

# Document Structure
def Html(*children, **attrs): return Tag("html", *children, **attrs)
def Head(*children, **attrs): return Tag("head", *children, **attrs)
def Body(*children, **attrs): return Tag("body", *children, **attrs)
def Title(*children, **attrs): return Tag("title", *children, **attrs)
def Meta(*children, **attrs): return Tag("meta", *children, **attrs)
def Link(*children, **attrs): return Tag("link", *children, **attrs)
def Style(*children, **attrs): return Tag("style", *children, **attrs)
def Script(*children, **attrs): return Tag("script", *children, **attrs)
def Base(*children, **attrs): return Tag("base", *children, **attrs)

# Text Content
def P(*children, **attrs): return Tag("p", *children, **attrs)
def H1(*children, **attrs): return Tag("h1", *children, **attrs)
def H2(*children, **attrs): return Tag("h2", *children, **attrs)
def H3(*children, **attrs): return Tag("h3", *children, **attrs)
def H4(*children, **attrs): return Tag("h4", *children, **attrs)
def H5(*children, **attrs): return Tag("h5", *children, **attrs)
def H6(*children, **attrs): return Tag("h6", *children, **attrs)
def Blockquote(*children, **attrs): return Tag("blockquote", *children, **attrs)
def Pre(*children, **attrs): return Tag("pre", *children, **attrs)
def Code(*children, **attrs): return Tag("code", *children, **attrs)
def Em(*children, **attrs): return Tag("em", *children, **attrs)
def Strong(*children, **attrs): return Tag("strong", *children, **attrs)
def Mark(*children, **attrs): return Tag("mark", *children, **attrs)
def Small(*children, **attrs): return Tag("small", *children, **attrs)
def Del(*children, **attrs): return Tag("del", *children, **attrs)
def Ins(*children, **attrs): return Tag("ins", *children, **attrs)
def Sub(*children, **attrs): return Tag("sub", *children, **attrs)
def Sup(*children, **attrs): return Tag("sup", *children, **attrs)
def Br(*children, **attrs): return Tag("br", *children, **attrs)
def Hr(*children, **attrs): return Tag("hr", *children, **attrs)

# Lists
def Ul(*children, **attrs): return Tag("ul", *children, **attrs)
def Ol(*children, **attrs): return Tag("ol", *children, **attrs)
def Li(*children, **attrs): return Tag("li", *children, **attrs)
def Dl(*children, **attrs): return Tag("dl", *children, **attrs)
def Dt(*children, **attrs): return Tag("dt", *children, **attrs)
def Dd(*children, **attrs): return Tag("dd", *children, **attrs)

# Links and Media
def A(*children, **attrs): return Tag("a", *children, **attrs)
def Img(*children, **attrs): return Tag("img", *children, **attrs)
def Picture(*children, **attrs): return Tag("picture", *children, **attrs)
def Source(*children, **attrs): return Tag("source", *children, **attrs)
def Video(*children, **attrs): return Tag("video", *children, **attrs)
def Audio(*children, **attrs): return Tag("audio", *children, **attrs)
def Track(*children, **attrs): return Tag("track", *children, **attrs)
def Map(*children, **attrs): return Tag("map", *children, **attrs)
def Area(*children, **attrs): return Tag("area", *children, **attrs)

# Forms
def Form(*children, **attrs): return Tag("form", *children, **attrs)
def Input(*children, **attrs): return Tag("input", *children, **attrs)
def Textarea(*children, **attrs): return Tag("textarea", *children, **attrs)
def Button(*children, **attrs): return Tag("button", *children, **attrs)
def Select(*children, **attrs): return Tag("select", *children, **attrs)
def Option(*children, **attrs): return Tag("option", *children, **attrs)
def Optgroup(*children, **attrs): return Tag("optgroup", *children, **attrs)
def Label(*children, **attrs): return Tag("label", *children, **attrs)
def Fieldset(*children, **attrs): return Tag("fieldset", *children, **attrs)
def Legend(*children, **attrs): return Tag("legend", *children, **attrs)
def Datalist(*children, **attrs): return Tag("datalist", *children, **attrs)
def Output(*children, **attrs): return Tag("output", *children, **attrs)
def Progress(*children, **attrs): return Tag("progress", *children, **attrs)
def Meter(*children, **attrs): return Tag("meter", *children, **attrs)

# Tables
def Table(*children, **attrs): return Tag("table", *children, **attrs)
def Caption(*children, **attrs): return Tag("caption", *children, **attrs)
def Colgroup(*children, **attrs): return Tag("colgroup", *children, **attrs)
def Col(*children, **attrs): return Tag("col", *children, **attrs)
def Thead(*children, **attrs): return Tag("thead", *children, **attrs)
def Tbody(*children, **attrs): return Tag("tbody", *children, **attrs)
def Tfoot(*children, **attrs): return Tag("tfoot", *children, **attrs)
def Tr(*children, **attrs): return Tag("tr", *children, **attrs)
def Th(*children, **attrs): return Tag("th", *children, **attrs)
def Td(*children, **attrs): return Tag("td", *children, **attrs)

# Containers
def Div(*children, **attrs): return Tag("div", *children, **attrs)
def Span(*children, **attrs): return Tag("span", *children, **attrs)
def Article(*children, **attrs): return Tag("article", *children, **attrs)
def Section(*children, **attrs): return Tag("section", *children, **attrs)
def Nav(*children, **attrs): return Tag("nav", *children, **attrs)
def Aside(*children, **attrs): return Tag("aside", *children, **attrs)
def Header(*children, **attrs): return Tag("header", *children, **attrs)
def Footer(*children, **attrs): return Tag("footer", *children, **attrs)
def Main(*children, **attrs): return Tag("main", *children, **attrs)
def Address(*children, **attrs): return Tag("address", *children, **attrs)

# Interactive Elements
def Details(*children, **attrs): return Tag("details", *children, **attrs)
def Summary(*children, **attrs): return Tag("summary", *children, **attrs)
def Dialog(*children, **attrs): return Tag("dialog", *children, **attrs)
def Menu(*children, **attrs): return Tag("menu", *children, **attrs)
def Menuitem(*children, **attrs): return Tag("menuitem", *children, **attrs)

# Embedded Content
def Embed(*children, **attrs): return Tag("embed", *children, **attrs)
def Object(*children, **attrs): return Tag("object", *children, **attrs)
def Param(*children, **attrs): return Tag("param", *children, **attrs)
def Iframe(*children, **attrs): return Tag("iframe", *children, **attrs)
def Canvas(*children, **attrs): return Tag("canvas", *children, **attrs)
def Svg(*children, **attrs): return Tag("svg", *children, **attrs)
def Math(*children, **attrs): return Tag("math", *children, **attrs)

# Semantic Elements
def Figure(*children, **attrs): return Tag("figure", *children, **attrs)
def Figcaption(*children, **attrs): return Tag("figcaption", *children, **attrs)
def Time(*children, **attrs): return Tag("time", *children, **attrs)
def Data(*children, **attrs): return Tag("data", *children, **attrs)
def Abbr(*children, **attrs): return Tag("abbr", *children, **attrs)
def Cite(*children, **attrs): return Tag("cite", *children, **attrs)
def Q(*children, **attrs): return Tag("q", *children, **attrs)
def Samp(*children, **attrs): return Tag("samp", *children, **attrs)
def Kbd(*children, **attrs): return Tag("kbd", *children, **attrs)
def Var(*children, **attrs): return Tag("var", *children, **attrs)
def Bdo(*children, **attrs): return Tag("bdo", *children, **attrs)
def Bdi(*children, **attrs): return Tag("bdi", *children, **attrs)
def Ruby(*children, **attrs): return Tag("ruby", *children, **attrs)
def Rt(*children, **attrs): return Tag("rt", *children, **attrs)
def Rp(*children, **attrs): return Tag("rp", *children, **attrs)
def Wbr(*children, **attrs): return Tag("wbr", *children, **attrs)

# Template
def Template(*children, **attrs): return Tag("template", *children, **attrs)
def Slot(*children, **attrs): return Tag("slot", *children, **attrs)

# Deprecated but still valid
def Center(*children, **attrs): return Tag("center", *children, **attrs)
def Font(*children, **attrs): return Tag("font", *children, **attrs)
def Strike(*children, **attrs): return Tag("strike", *children, **attrs)
def Big(*children, **attrs): return Tag("big", *children, **attrs)
def Tt(*children, **attrs): return Tag("tt", *children, **attrs) 